spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/world-db
    username: world
    password: world123

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  jpa:
    hibernate:
      ddl: create